= Hybrid chart approach with validation in Openshift

:home: https://github.com/ammbra

* <<preparation , Preparation>>
** <<working-locally-with-the-docker-image-for-visitor-microservice, Working locally with the Docker image for Visitor Microservice>>
* <<install-leader-chart-for-landmark-microservice, Install leader chart for Landmark microservice >>
** <<working-locally-with-the-docker-image-for-landmark-microservice, Working locally with the Docker image for Landmark Microservice>>
** <<leader-helm-chart-installation, Leader Helm chart installation>>
* <<install-helm-chart-for-visitor-microservice, Install Helm chart for Visitor microservice>>
* <<compatibility,Compatibility>>
* <<license,License>>

This approach means to create one 'leader' chart per service group, while keeping
one dependent chart per service, having values and specific aditions.

**Goal of this section: deploy the visitor and landmark microservices using Helm charts that have additional JSON schema validation.
**

Leader chart approach (with validation) will be used for deploying landmark microservice, while visitor microservice will be deployed via chart per service approach.

All the below commands will be executed in a terminal window.

=== Preparation
To login to the OpenShift cluster from the Terminal run:

[source, bash, subs="normal,attributes"]
----
$ oc login -u kubeadmin -p YOUR_SECRET_PASSWORD https://api.crc.testing:6443
----
Check if you already have the _dev_ project:
----
$ oc get project
$ oc new-project dev
$ oc project dev
----

The landmark microservice will persist its data into a database, in this case a PostgreSQL database instance.

Check if the Helm repo https://charts.bitnami.com/bitnami[https://charts.bitnami.com/bitnami] is added to your existing list:
[source, bash, subs="normal,attributes"]
----
$ helm repo list
----
If the repo is not there, please run the following set of commands:
[source, bash, subs="normal,attributes"]
----
$ helm repo add bitnami https://charts.bitnami.com/bitnami
----

==== Working locally with the Docker image for Visitor Microservice
Clone the repository {home}/visitor:
[source, bash, subs="normal,attributes"]
----
$ git clone {home}/visitor.git
$ git checkout -b validation/hybrid-chart-lab
$ git pull
----

Try to build the project locally using {home}/visitor/blob/validation/hybrid-chart-lab/Run-Visitor-Microservice.adoc[Run-Landmark-Microservice.adoc].

Build the image with:
[source, bash, subs="normal,attributes"]
----
$ docker run -d -p 5000:5000 --restart=always --name registry registry:2docker run -d -p 5000:5000 --restart=always --name registry registry:2
$ docker build -t springboot/visitor:1.0 .
$ docker tag springboot/visitor:1.0 localhost:5000/springboot/visitor:1.0
$ docker push localhost:5000/springboot/visitor:1.0
----

=== Install leader chart for Landmark microservice
IMPORTANT: If you already have the Docker image for Landmark Microservice and/or the installation of the leader charts,
skip these steps and just install the <<install-helm-chart-for-visitor-microservice, visitor charts >>.


==== Working locally with the Docker image for Landmark Microservice

Clone the repository {home}/landmark.
[source, bash, subs="normal,attributes"]
----
$ git clone {home}/landmark.git
$ git checkout -b validation/leader-chart-lab
$ git pull
----

Make sure that you are under root folder of the clone repository (_landmark_) and run:
[source, bash, subs="normal,attributes"]
----
$ mvn package
----
Then, build the image with:
[source, bash, subs="normal,attributes"]
----
$ docker run -d -p 5000:5000 --restart=always --name registry registry:2
$ docker build -f src/main/docker/Dockerfile.jvm -t quarkus/landmark:1.0 .
$ docker tag quarkus/landmark:1.0 localhost:5000/quarkus/landmark:1.0
$ docker push localhost:5000/quarkus/landmark:1.0
----


==== Leader Helm chart installation
Inspect the validation of the leader charts before installing them.

You will notice a _values.<>.schema.json_ next to _values.yaml_ file; the JSON schema validation is an additional step that ensures correctness of your chart values.

Install your charts in your current project:

[source, bash, subs="normal,attributes"]
----
$ helm install leader ./leader
$ helm status leader
----

=== Install Helm chart for Visitor microservice
Return to the root folder of visitor microservice (_visitor_).
You will notice a _values.schema.json_ next to the _values.yaml_ file; the JSON schema validation is an additional step that ensures correctness of your chart values.


[source, bash, subs="normal,attributes"]
----
$ cd chart
$ helm install visitor ./visitor
$ helm status visitor
$ kubectl get ns
$ kubectl get svc
$ kubectl port-forward --namespace qa svc/visitor 8080
----

Go in a browser window and copy-paste http://localhost:8080/api/visit/museum/ams

*Congratulations*, you visited a landmark by using two microservices!

|===
|{home}/helm-openshift-workshop[Navigate to global instructions] | {home}/visitor[Navigate to previous section]
|===

'''
=== Compatibility

The Java code in the repositories is compatible with Java11.

'''
=== License

This code is dedicated to the public domain to the maximum extent permitted by applicable law, pursuant to http://creativecommons.org/publicdomain/zero/1.0/[CC0].
