apiVersion: v1
kind: Service
metadata:
  name: {{ include "visitor.fullname" . }}
  labels:
    {{- include "visitor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.port }}
      nodePort: {{ .Values.service.ports.nodePort}}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "visitor.selectorLabels" . | nindent 4 }}
