{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "visitor.serviceAccountName" . }}
  labels:
{{ include "visitor.labels" . | nindent 4 }}
{{- end -}}
